
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ScriptScene } from "../types";

export const exportToPdf = (script: ScriptScene[], userName?: string) => {
  const doc = new jsPDF();
  const title = "Skrip Video Edukasi";
  const date = new Date().toLocaleDateString('id-ID');

  // Set default text color to #0e0e0e (RGB: 14, 14, 14)
  const textColor = [14, 14, 14];

  // Header
  doc.setFontSize(18);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text(title, 14, 22);
  
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Generated by VideoScript Generator - ${date}`, 14, 30);
  
  if (userName) {
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(`Presenter: ${userName}`, 14, 36);
  }

  // Table Data Preparation
  const tableData = script.map(s => [
    s.scene, 
    s.narasi, 
    Array.isArray(s.kalimatKunci) ? s.kalimatKunci.join('\n• ') : s.kalimatKunci, 
    s.visual
  ]);
  
  autoTable(doc, {
    startY: userName ? 42 : 36,
    head: [["Scene", "Narasi", "Kalimat Kunci", "Visual (Prompt)"]],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234], textColor: 255 },
    bodyStyles: { textColor: [14, 14, 14], fontSize: 8 },
    styles: { cellPadding: 3, overflow: 'linebreak' },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 85 },
      2: { cellWidth: 45 },
      3: { cellWidth: 45 }
    },
    didDrawPage: (data) => {
      // Footer
      const footerText = "Dikembangkan oleh Pramudya | munadipramudya@gmail.com";
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      
      doc.setFontSize(6);
      doc.setTextColor(128, 128, 128);
      doc.text(footerText, data.settings.margin.left, pageHeight - 10, { align: "left" });
      doc.text(`Halaman ${data.pageNumber}`, pageSize.width - data.settings.margin.right, pageHeight - 10, { align: "right" });
    }
  });

  doc.save(`Skrip_Video_${date.replace(/\//g, '-')}.pdf`);
};
